### PR TITLE
Update factors.lua -- Missing Value/Factor

### PR DESCRIPTION
**Pull request by OMGhixD-OG**
Kept getting message "unknown mount", so i added it to the factors.lua, I'm not sure if the secondary value is/was accurate. But i based it on the kodo. I'm also a tauren on retail.. so almost biggest character model?

Nonetheless, i applied and tested. it looks and feels fine. The error also dissapeared

### CODE REVIEW

**Comment by LudiusMaximus** [comment]
Hello, and thank you very much for your contribution. But typically, when you use a mount not yet in the files, the console messages should let you click on the link which opens the window in which you can configure and safe a custom factor. Did this not work for you?

**Comment by OMGhixD-OG** [comment]
> Hello, and thank you very much for your contribution. But typically, when you use a mount not yet in the files, the console messages should let you click on the link which opens the window in which you can configure and safe a custom factor. Did this not work for you?

I do get the prompt, but yeah no nothing happens when i click the "add this mount" button thingie.

**Comment by LudiusMaximus** [comment]
Is it because you are playing a Dracthyr, maybe?

**Comment by OMGhixD-OG** [comment]
> Is it because you are playing a Dracthyr, maybe?

Not at all, i play a Tauren Druid : )

**Comment by LudiusMaximus** [comment]
Hm, not sure if we are talking about the same thing then.

When you mount a not yet known mount, you get this console message:
image

Clicking the link opens this:
image


I just checked and it works for me.

**Pull request closed without merging**
